### ISSUE TITLE
Self-healing schema based on required fields

### ISSUE THREAD

**Issue by amirsaffari** [podio/valideer#16]
I'm trying to create validators that based on the required flag are able to fix their data. Let me give you an example of the expected behaviour: consider the following schema
```python
schema = {
    '+name': valideer.AdaptTo(unicode),
    'price': valideer.AdaptTo(float),
}
_validator = valideer.parse(schema)
```
and the data as
```python
data = {
    'name': 'valideer is great',
    'price': "it's open source",
}
```
If you validate this, you will get the expected error. However, since the *price* is optional, if validator removed this field, it will fix the data. So I would like
```python
_validator.validate(data)
```
to return
```
{
    'name': 'valideer is great',
}
```
 I have checked the code and I think this can be done by modifying the logic inside 
```python
class Object(Type):
    ...
    def validate(...
        ...
        for name, validator in self._named_validators:
```
but wanted to see if there's any alternative that can be done.

Thanks

**Comment by gsakkis** [comment]
Indeed that's not currently possible in `valideer` but it's not hard to add it, though not quite trivial either. Basically it needs another parameter to explicitly enable this behaviour in `valideer.parse()`, similarly to `required_properties`, since it's backwards incompatible with the existing semantics of optional fields. I'll try to add it shortly, thanks for the input.

**Comment by gsakkis** [comment]
Pushed at f3822f7b1aee657ad5b1d66cc3c713ce40ac54c6, let me know if that works for you and I'll cut a new release on PyPI.

**Comment by amirsaffari** [comment]
Awesome, thanks. I tested with my setup and indeed it works as specified.
